// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.codebattery.mmb.domain;

import com.codebattery.mmb.domain.SysUser;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect SysUser_Roo_Configurable {
    
    declare @type: SysUser: @Configurable;
    
}
