// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.codebattery.mmb.domain;

import com.codebattery.mmb.domain.SysUser;

privileged aspect SysUser_Roo_JavaBean {
    
    public String SysUser.getName() {
        return this.name;
    }
    
    public void SysUser.setName(String name) {
        this.name = name;
    }
    
}
