// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.codebattery.mmb.domain;

import com.codebattery.mmb.dao.SysUserDao;
import com.codebattery.mmb.domain.SysUserDataOnDemand;
import com.codebattery.mmb.domain.SysUserIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect SysUserIntegrationTest_Roo_IntegrationTest {
    
    declare @type: SysUserIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: SysUserIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: SysUserIntegrationTest: @Transactional;
    
    @Autowired
    SysUserDataOnDemand SysUserIntegrationTest.dod;
    
    @Autowired
    SysUserDao SysUserIntegrationTest.sysUserDao;
    
    @Test
    public void SysUserIntegrationTest.testCount() {
        Assert.assertNotNull("Data on demand for 'SysUser' failed to initialize correctly", dod.getRandomSysUser());
        long count = sysUserDao.count();
        Assert.assertTrue("Counter for 'SysUser' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void SysUserIntegrationTest.testFind() {
        SysUser obj = dod.getRandomSysUser();
        Assert.assertNotNull("Data on demand for 'SysUser' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'SysUser' failed to provide an identifier", id);
        obj = sysUserDao.findOne(id);
        Assert.assertNotNull("Find method for 'SysUser' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'SysUser' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void SysUserIntegrationTest.testFindAll() {
        Assert.assertNotNull("Data on demand for 'SysUser' failed to initialize correctly", dod.getRandomSysUser());
        long count = sysUserDao.count();
        Assert.assertTrue("Too expensive to perform a find all test for 'SysUser', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<SysUser> result = sysUserDao.findAll();
        Assert.assertNotNull("Find all method for 'SysUser' illegally returned null", result);
        Assert.assertTrue("Find all method for 'SysUser' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void SysUserIntegrationTest.testFindEntries() {
        Assert.assertNotNull("Data on demand for 'SysUser' failed to initialize correctly", dod.getRandomSysUser());
        long count = sysUserDao.count();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<SysUser> result = sysUserDao.findAll(new org.springframework.data.domain.PageRequest(firstResult / maxResults, maxResults)).getContent();
        Assert.assertNotNull("Find entries method for 'SysUser' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'SysUser' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void SysUserIntegrationTest.testFlush() {
        SysUser obj = dod.getRandomSysUser();
        Assert.assertNotNull("Data on demand for 'SysUser' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'SysUser' failed to provide an identifier", id);
        obj = sysUserDao.findOne(id);
        Assert.assertNotNull("Find method for 'SysUser' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifySysUser(obj);
        Integer currentVersion = obj.getVersion();
        sysUserDao.flush();
        Assert.assertTrue("Version for 'SysUser' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void SysUserIntegrationTest.testSaveUpdate() {
        SysUser obj = dod.getRandomSysUser();
        Assert.assertNotNull("Data on demand for 'SysUser' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'SysUser' failed to provide an identifier", id);
        obj = sysUserDao.findOne(id);
        boolean modified =  dod.modifySysUser(obj);
        Integer currentVersion = obj.getVersion();
        SysUser merged = sysUserDao.save(obj);
        sysUserDao.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'SysUser' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void SysUserIntegrationTest.testSave() {
        Assert.assertNotNull("Data on demand for 'SysUser' failed to initialize correctly", dod.getRandomSysUser());
        SysUser obj = dod.getNewTransientSysUser(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'SysUser' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'SysUser' identifier to be null", obj.getId());
        try {
            sysUserDao.save(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        sysUserDao.flush();
        Assert.assertNotNull("Expected 'SysUser' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void SysUserIntegrationTest.testDelete() {
        SysUser obj = dod.getRandomSysUser();
        Assert.assertNotNull("Data on demand for 'SysUser' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'SysUser' failed to provide an identifier", id);
        obj = sysUserDao.findOne(id);
        sysUserDao.delete(obj);
        sysUserDao.flush();
        Assert.assertNull("Failed to remove 'SysUser' with identifier '" + id + "'", sysUserDao.findOne(id));
    }
    
}
